<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMzNDZd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMzNDZd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAMzNDZd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAMzNDZd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAMzNDZd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AMzNDZd',
    'container.build_id' => '6583b139',
    'container.build_time' => 1590610149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMzNDZd');
